# Master branch
-
  configuration: build and deploy

  branches:
    only:
    - master

  environment:
    PYTHON: "C:\\Python34_64"
    PYTHON_VERSION: "3.4"
    PYTHON_ARCH: "64"
    CONDA_BLD_PATH: "C:\\conda-bld"
    binstar_token:
      secure: aE8S0M8ihg/xtnOgn8LIuDyGd/JI3v4sBQshdj6FL8VBOyVcqET4mOLCh3sKTtiP

  install:
    # Install Miniconda
    - ps: .\\continuous-integration\\appveyor\\install.ps1
    - ps: $env:Path = "$env:PYTHON;$env:PYTHON\\Scripts;$env:Path"

  build_script:
    - ps: ./build

  deploy_script:
    - ps: ./deploy

# Other branches
-
  configuration: build

  branches:
    except:
    - master

  environment:
    PYTHON: "C:\\Python34_64"
    PYTHON_VERSION: "3.4"
    PYTHON_ARCH: "64"
    CONDA_BLD_PATH: "C:\\conda-bld"

  install:
    # Install Miniconda
    - ps: .\\continuous-integration\\appveyor\\install.ps1
    - ps: $env:Path = "$env:PYTHON;$env:PYTHON\\Scripts;$env:Path"

  build_script:
    - ps: ./build

  artifacts:
    # Archive the generated conda package in the ci.appveyor.com build report.
    - path: "%CONDA_BLD_PATH%\\win-64\\*.tar.bz2"
