# Master branch
-
  configuration: Build and deploy

  branches:
    only:
    - master

  environment:
    CONDA_BLD_PATH: "C:\\conda-bld"
    binstar_token:
      secure: aE8S0M8ihg/xtnOgn8LIuDyGd/JI3v4sBQshdj6FL8VBOyVcqET4mOLCh3sKTtiP

  install:
  - ps: ./install_conda
  - ps: conda update --quiet conda
  - ps: conda install --quiet conda-build anaconda-client

  build_script:
  - ps: ./build

  deploy_script:
  - ps: ./deploy

# Other branches
-
  configuration: Build

  branches:
    except:
    - master

  environment:
    CONDA_BLD_PATH: "C:\\conda-bld"

  install:
  - ps: ./install_conda
  - ps: conda update --quiet conda
  - ps: conda install --quiet conda-build anaconda-client

  build_script:
  - ps: ./build

  artifacts:
    # Archive the generated conda package in the ci.appveyor.com build report.
  - path: "%CONDA_BLD_PATH%\\win-64\\*.tar.bz2"
