package:
  name: conda_macros
  version: 0.4.1

source:
  git_url: https://github.com/faph/NSIS-Conda-Macros.git
  git_tag: v0.4.1

build:
  string: nsis_0

requirements:
  build: []
  run:
  - nsis
  - execdos
  - nsarray

about:
  home: https://github.com/faph/NSIS-Conda-Macros
  license: MIT
  license_file: LICENSE
  summary: Install conda applications using NSIS.
  readme: README.md
