package:
  name: execdos
  version: 1.0.1.3

build:
  string: nsis_0

source:
  fn: ExecDos.zip
  url: http://nsis.sourceforge.net/mediawiki/images/0/0f/ExecDos.zip

requirements:
  build: []
  run: []
