package:
  name: nsjson
  version: 1.1.0.2

build:
  string: nsis_0

source:
  fn: NsJSON.zip
  url: http://nsis.sourceforge.net/mediawiki/images/f/f0/NsJSON.zip
  md5: 20ff8fd1ba80e01c2160531aac0a9ee3
  sha1: d0c185de8166cf0d910af52a6f6600224d6b85c8

requirements:
  build: []
  run:
  - nsis

about:
  summary: nsJSON plugin for NSIS
  home: http://nsis.sourceforge.net/NsJSON_plug-in
